---
- name: Install Composer dependencies
  composer:
    command: install
    executable: "{{ current_php_executable }}"
    arguments: --optimize-autoloader
    working_dir: "{{ deploy_helper.new_release_path }}"
    no_dev: "{{ 'no' if env == 'development' else 'yes' }}"
