---
- name: Build laravel config cache
  shell: "{{ current_php_executable }} artisan config:cache"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  register: config_cache_result
  ignore_errors: yes

- name: Inform about inability to cache config
  debug:
    msg: Config could not be cached. Are you using lumen?
  when: '"no commands defined" in config_cache_result.stdout'

- name: Build laravel route cache
  shell: "{{ current_php_executable }} artisan route:cache"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  register: route_cache_result
  ignore_errors: yes

- name: Inform about inability to cache routes due to Closure
  debug:
    msg: Routes could not be cached due to a Closure. In order to have routes cached, you may only define controller routes.
  when: '"Closure" in route_cache_result.stdout'
