---
- name: Check if keys for Passport are present
  stat:
    path: "{{ deploy_helper.shared_path }}/storage/oauth-private.key"
  register: key_file

- name: Generate keys for Laravel Passport
  shell: "{{ current_php_executable }} artisan passport:keys"
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  when: not key_file.stat.exists
